xilinx-zynqmp: fix gstream bad plugins compiling error
RallyID: US112355

gstream1.0-plugins-bad needs to directly include libxdamage, libxfixes, and kms
for our build system to populate their sysroot into gstream1.0-plugins-bad recipe
in some situation and avoid the following error messages:

gstreamer1.0-plugins-bad/1.12.2-r0/recipe-sysroot-native/usr/bin/aarch64-wrs-linux/../../libexec/aarch64-wrs-linux/gcc/aarch64-wrs-linux/7.3.0/ld: warning: libdrm.so.2, needed by /buildarea/raid5/zchen/wr10-zynqmp-0408-std/build/tmp-glibc/work/aarch64-wrs-linux/gstreamer1.0-plugins-bad/1.12.2-r0/recipe-sysroot/usr/lib64/libGLESv2.so, not found (try using -rpath or -rpath-link)
gstreamer1.0-plugins-bad/1.12.2-r0/recipe-sysroot-native/usr/bin/aarch64-wrs-linux/../../libexec/aarch64-wrs-linux/gcc/aarch64-wrs-linux/7.3.0/ld: warning: libXfixes.so.3, needed by /buildarea/raid5/zchen/wr10-zynqmp-0408-std/build/tmp-glibc/work/aarch64-wrs-linux/gstreamer1.0-plugins-bad/1.12.2-r0/recipe-sysroot/usr/lib64/libGLESv2.so, not found (try using -rpath or -rpath-link)
gstreamer1.0-plugins-bad/1.12.2-r0/recipe-sysroot-native/usr/bin/aarch64-wrs-linux/../../libexec/aarch64-wrs-linux/gcc/aarch64-wrs-linux/7.3.0/ld: warning: libXdamage.so.1, needed by /buildarea/raid5/zchen/wr10-zynqmp-0408-std/build/tmp-glibc/work/aarch64-wrs-linux/gstreamer1.0-plugins-bad/1.12.2-r0/recipe-sysroot/usr/lib64/libGLESv2.so, not found (try using -rpath or -rpath-link)
gstreamer1.0-plugins-bad/1.12.2-r0/recipe-sysroot/usr/lib64/libGLESv2.so: undefined reference to `drmGetMagic'
gstreamer1.0-plugins-bad/1.12.2-r0/recipe-sysroot/usr/lib64/libGLESv2.so: undefined reference to `XFixesDestroyRegion'
gstreamer1.0-plugins-bad/1.12.2-r0/recipe-sysroot/usr/lib64/libGLESv2.so: undefined reference to `XDamageAdd'
gstreamer1.0-plugins-bad/1.12.2-r0/recipe-sysroot/usr/lib64/libGLESv2.so: undefined reference to `XFixesCreateRegion'
| collect2: error: ld returned 1 exit status

Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>